server:
  port: 8889
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: homestead
    password: secret
    url: jdbc:mysql://127.0.0.1:33060/javavue?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true